### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by rakesh2215** [krcb197/PeakRDL-cheader#1]
python3 -m pip install peakrdl-cheader
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement peakrdl-cheader (from versions: none)
ERROR: No matching distribution found for peakrdl-cheader
WARNING: You are using pip version 20.2.3; however, version 22.2.2 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

Please note that I was able to install other PeakRDL packages (ipxact, regblock etc).

**Comment by krcb197** [comment]
I am still developing this package, however, this issue has spurned me to make the first version. This can build the C #defines for the case of an address map with register only. I will add support for register files, arrays etc.... as I go.

Thank you for taking an interesting in my project
